//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDatLichMuon
    {
        public string MaChiTiet { get; set; }
        public string MaLichMuon { get; set; }
        public string MaSach { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual DatLichMuon DatLichMuon { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
