//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatLichMuon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatLichMuon()
        {
            this.ChiTietDatLichMuons = new HashSet<ChiTietDatLichMuon>();
        }
    
        public string MaLichMuon { get; set; }
        public string MaDocGia { get; set; }
        public System.DateTime NgayDenMuon { get; set; }
        public System.TimeSpan GioDenMuon { get; set; }
        public string TrangThai { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDatLichMuon> ChiTietDatLichMuons { get; set; }
        public virtual DocGia DocGia { get; set; }
    }
}
