//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LienHe
    {
        public string MaLienHe { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public string Sdt { get; set; }
        public string Chude { get; set; }
        public string NoiDung { get; set; }
        public string FileDinhKem { get; set; }
        public Nullable<System.DateTime> ThoiGianGui { get; set; }
    }
}
