//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanHoi
    {
        public string MaPhanHoi { get; set; }
        public string MaDocGia { get; set; }
        public string MaSach { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayGui { get; set; }
        public string TrangThai { get; set; }
        public string PhanHoiAdmin { get; set; }
    
        public virtual DocGia DocGia { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
