//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        {
            this.ChiTietDatLichMuons = new HashSet<ChiTietDatLichMuon>();
            this.ChiTietPhieuMuons = new HashSet<ChiTietPhieuMuon>();
            this.PhanHois = new HashSet<PhanHoi>();
        }
    
        public string MaSach { get; set; }
        public string TenSach { get; set; }
        public string MaTacGia { get; set; }
        public string MaTheLoai { get; set; }
        public string MaNXB { get; set; }
        public Nullable<int> NamXuatBan { get; set; }
        public int SoLuong { get; set; }
        public string AnhBia { get; set; }
        public string GhiChu { get; set; }
        public Nullable<decimal> GiaTien { get; set; }
        public string MaViTri { get; set; }
        public Nullable<int> SoLanTaiBan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDatLichMuon> ChiTietDatLichMuons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuMuon> ChiTietPhieuMuons { get; set; }
        public virtual NhaXuatBan NhaXuatBan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanHoi> PhanHois { get; set; }
        public virtual TacGia TacGia { get; set; }
        public virtual TheLoai TheLoai { get; set; }
        public virtual ViTri ViTri { get; set; }
    }
}
